bp_andela_media_database:           'bp-andela-media'
bp_andela_media_database_password:  ''
bp_andela_media_database_username:  'postgres'
bp_andela_media_database_port:      '5432'
bp_andela_media_test_database:      'bp-andela-media-development'
bp_andela_media_database_host:      'localhost'
